package com.olvind.mui.csstype.mod

import com.olvind.mui.csstype.mod.Property._AccentColor
import com.olvind.mui.csstype.mod.Property._AlignContent
import com.olvind.mui.csstype.mod.Property._AlignItems
import com.olvind.mui.csstype.mod.Property._AlignSelf
import com.olvind.mui.csstype.mod.Property._AlignTracks
import com.olvind.mui.csstype.mod.Property._Animation
import com.olvind.mui.csstype.mod.Property._AnimationDirection
import com.olvind.mui.csstype.mod.Property._AnimationFillMode
import com.olvind.mui.csstype.mod.Property._AnimationIterationCount
import com.olvind.mui.csstype.mod.Property._AnimationName
import com.olvind.mui.csstype.mod.Property._AnimationPlayState
import com.olvind.mui.csstype.mod.Property._AnimationTimingFunction
import com.olvind.mui.csstype.mod.Property._AspectRatio
import com.olvind.mui.csstype.mod.Property._Azimuth
import com.olvind.mui.csstype.mod.Property._BackdropFilter
import com.olvind.mui.csstype.mod.Property._Background
import com.olvind.mui.csstype.mod.Property._BackgroundAttachment
import com.olvind.mui.csstype.mod.Property._BackgroundBlendMode
import com.olvind.mui.csstype.mod.Property._BackgroundClip
import com.olvind.mui.csstype.mod.Property._BackgroundColor
import com.olvind.mui.csstype.mod.Property._BackgroundImage
import com.olvind.mui.csstype.mod.Property._BackgroundOrigin
import com.olvind.mui.csstype.mod.Property._BackgroundPosition
import com.olvind.mui.csstype.mod.Property._BackgroundPositionX
import com.olvind.mui.csstype.mod.Property._BackgroundPositionY
import com.olvind.mui.csstype.mod.Property._BackgroundRepeat
import com.olvind.mui.csstype.mod.Property._BackgroundSize
import com.olvind.mui.csstype.mod.Property._BaselineShift
import com.olvind.mui.csstype.mod.Property._BlockOverflow
import com.olvind.mui.csstype.mod.Property._BlockSize
import com.olvind.mui.csstype.mod.Property._Border
import com.olvind.mui.csstype.mod.Property._BorderBlock
import com.olvind.mui.csstype.mod.Property._BorderBlockColor
import com.olvind.mui.csstype.mod.Property._BorderBlockEnd
import com.olvind.mui.csstype.mod.Property._BorderBlockEndColor
import com.olvind.mui.csstype.mod.Property._BorderBlockEndWidth
import com.olvind.mui.csstype.mod.Property._BorderBlockStart
import com.olvind.mui.csstype.mod.Property._BorderBlockStartColor
import com.olvind.mui.csstype.mod.Property._BorderBlockStartWidth
import com.olvind.mui.csstype.mod.Property._BorderBlockWidth
import com.olvind.mui.csstype.mod.Property._BorderBottom
import com.olvind.mui.csstype.mod.Property._BorderBottomColor
import com.olvind.mui.csstype.mod.Property._BorderBottomWidth
import com.olvind.mui.csstype.mod.Property._BorderColor
import com.olvind.mui.csstype.mod.Property._BorderImage
import com.olvind.mui.csstype.mod.Property._BorderImageRepeat
import com.olvind.mui.csstype.mod.Property._BorderImageSource
import com.olvind.mui.csstype.mod.Property._BorderImageWidth
import com.olvind.mui.csstype.mod.Property._BorderInline
import com.olvind.mui.csstype.mod.Property._BorderInlineColor
import com.olvind.mui.csstype.mod.Property._BorderInlineEnd
import com.olvind.mui.csstype.mod.Property._BorderInlineEndColor
import com.olvind.mui.csstype.mod.Property._BorderInlineEndWidth
import com.olvind.mui.csstype.mod.Property._BorderInlineStart
import com.olvind.mui.csstype.mod.Property._BorderInlineStartColor
import com.olvind.mui.csstype.mod.Property._BorderInlineStartWidth
import com.olvind.mui.csstype.mod.Property._BorderInlineWidth
import com.olvind.mui.csstype.mod.Property._BorderLeft
import com.olvind.mui.csstype.mod.Property._BorderLeftColor
import com.olvind.mui.csstype.mod.Property._BorderLeftWidth
import com.olvind.mui.csstype.mod.Property._BorderRight
import com.olvind.mui.csstype.mod.Property._BorderRightColor
import com.olvind.mui.csstype.mod.Property._BorderRightWidth
import com.olvind.mui.csstype.mod.Property._BorderStyle
import com.olvind.mui.csstype.mod.Property._BorderTop
import com.olvind.mui.csstype.mod.Property._BorderTopColor
import com.olvind.mui.csstype.mod.Property._BorderTopWidth
import com.olvind.mui.csstype.mod.Property._BorderWidth
import com.olvind.mui.csstype.mod.Property._Bottom
import com.olvind.mui.csstype.mod.Property._BoxShadow
import com.olvind.mui.csstype.mod.Property._CaretColor
import com.olvind.mui.csstype.mod.Property._Clip
import com.olvind.mui.csstype.mod.Property._ClipPath
import com.olvind.mui.csstype.mod.Property._Color
import com.olvind.mui.csstype.mod.Property._ColorScheme
import com.olvind.mui.csstype.mod.Property._ColumnCount
import com.olvind.mui.csstype.mod.Property._ColumnGap
import com.olvind.mui.csstype.mod.Property._ColumnRule
import com.olvind.mui.csstype.mod.Property._ColumnRuleColor
import com.olvind.mui.csstype.mod.Property._ColumnRuleStyle
import com.olvind.mui.csstype.mod.Property._ColumnRuleWidth
import com.olvind.mui.csstype.mod.Property._ColumnWidth
import com.olvind.mui.csstype.mod.Property._Columns
import com.olvind.mui.csstype.mod.Property._Contain
import com.olvind.mui.csstype.mod.Property._Content
import com.olvind.mui.csstype.mod.Property._CounterIncrement
import com.olvind.mui.csstype.mod.Property._CounterReset
import com.olvind.mui.csstype.mod.Property._CounterSet
import com.olvind.mui.csstype.mod.Property._Cursor
import com.olvind.mui.csstype.mod.Property._Display
import com.olvind.mui.csstype.mod.Property._Fill
import com.olvind.mui.csstype.mod.Property._Filter
import com.olvind.mui.csstype.mod.Property._Flex
import com.olvind.mui.csstype.mod.Property._FlexBasis
import com.olvind.mui.csstype.mod.Property._FlexFlow
import com.olvind.mui.csstype.mod.Property._FloodColor
import com.olvind.mui.csstype.mod.Property._Font
import com.olvind.mui.csstype.mod.Property._FontFamily
import com.olvind.mui.csstype.mod.Property._FontFeatureSettings
import com.olvind.mui.csstype.mod.Property._FontLanguageOverride
import com.olvind.mui.csstype.mod.Property._FontSize
import com.olvind.mui.csstype.mod.Property._FontSizeAdjust
import com.olvind.mui.csstype.mod.Property._FontSmooth
import com.olvind.mui.csstype.mod.Property._FontStretch
import com.olvind.mui.csstype.mod.Property._FontStyle
import com.olvind.mui.csstype.mod.Property._FontSynthesis
import com.olvind.mui.csstype.mod.Property._FontVariant
import com.olvind.mui.csstype.mod.Property._FontVariantAlternates
import com.olvind.mui.csstype.mod.Property._FontVariantEastAsian
import com.olvind.mui.csstype.mod.Property._FontVariantLigatures
import com.olvind.mui.csstype.mod.Property._FontVariantNumeric
import com.olvind.mui.csstype.mod.Property._FontVariationSettings
import com.olvind.mui.csstype.mod.Property._FontWeight
import com.olvind.mui.csstype.mod.Property._Gap
import com.olvind.mui.csstype.mod.Property._GlyphOrientationVertical
import com.olvind.mui.csstype.mod.Property._Grid
import com.olvind.mui.csstype.mod.Property._GridAutoColumns
import com.olvind.mui.csstype.mod.Property._GridAutoFlow
import com.olvind.mui.csstype.mod.Property._GridAutoRows
import com.olvind.mui.csstype.mod.Property._GridTemplate
import com.olvind.mui.csstype.mod.Property._GridTemplateAreas
import com.olvind.mui.csstype.mod.Property._GridTemplateColumns
import com.olvind.mui.csstype.mod.Property._GridTemplateRows
import com.olvind.mui.csstype.mod.Property._HangingPunctuation
import com.olvind.mui.csstype.mod.Property._Height
import com.olvind.mui.csstype.mod.Property._ImageOrientation
import com.olvind.mui.csstype.mod.Property._ImageResolution
import com.olvind.mui.csstype.mod.Property._InitialLetter
import com.olvind.mui.csstype.mod.Property._InlineSize
import com.olvind.mui.csstype.mod.Property._Inset
import com.olvind.mui.csstype.mod.Property._InsetBlock
import com.olvind.mui.csstype.mod.Property._InsetBlockEnd
import com.olvind.mui.csstype.mod.Property._InsetBlockStart
import com.olvind.mui.csstype.mod.Property._InsetInline
import com.olvind.mui.csstype.mod.Property._InsetInlineEnd
import com.olvind.mui.csstype.mod.Property._InsetInlineStart
import com.olvind.mui.csstype.mod.Property._JustifyContent
import com.olvind.mui.csstype.mod.Property._JustifyItems
import com.olvind.mui.csstype.mod.Property._JustifySelf
import com.olvind.mui.csstype.mod.Property._JustifyTracks
import com.olvind.mui.csstype.mod.Property._Left
import com.olvind.mui.csstype.mod.Property._LetterSpacing
import com.olvind.mui.csstype.mod.Property._LightingColor
import com.olvind.mui.csstype.mod.Property._LineClamp
import com.olvind.mui.csstype.mod.Property._LineHeight
import com.olvind.mui.csstype.mod.Property._ListStyle
import com.olvind.mui.csstype.mod.Property._ListStyleImage
import com.olvind.mui.csstype.mod.Property._ListStyleType
import com.olvind.mui.csstype.mod.Property._Margin
import com.olvind.mui.csstype.mod.Property._MarginBlock
import com.olvind.mui.csstype.mod.Property._MarginBlockEnd
import com.olvind.mui.csstype.mod.Property._MarginBlockStart
import com.olvind.mui.csstype.mod.Property._MarginBottom
import com.olvind.mui.csstype.mod.Property._MarginInline
import com.olvind.mui.csstype.mod.Property._MarginInlineEnd
import com.olvind.mui.csstype.mod.Property._MarginInlineStart
import com.olvind.mui.csstype.mod.Property._MarginLeft
import com.olvind.mui.csstype.mod.Property._MarginRight
import com.olvind.mui.csstype.mod.Property._MarginTop
import com.olvind.mui.csstype.mod.Property._Marker
import com.olvind.mui.csstype.mod.Property._MarkerEnd
import com.olvind.mui.csstype.mod.Property._MarkerMid
import com.olvind.mui.csstype.mod.Property._MarkerStart
import com.olvind.mui.csstype.mod.Property._Mask
import com.olvind.mui.csstype.mod.Property._MaskBorder
import com.olvind.mui.csstype.mod.Property._MaskBorderRepeat
import com.olvind.mui.csstype.mod.Property._MaskBorderSource
import com.olvind.mui.csstype.mod.Property._MaskBorderWidth
import com.olvind.mui.csstype.mod.Property._MaskClip
import com.olvind.mui.csstype.mod.Property._MaskComposite
import com.olvind.mui.csstype.mod.Property._MaskImage
import com.olvind.mui.csstype.mod.Property._MaskMode
import com.olvind.mui.csstype.mod.Property._MaskOrigin
import com.olvind.mui.csstype.mod.Property._MaskPosition
import com.olvind.mui.csstype.mod.Property._MaskRepeat
import com.olvind.mui.csstype.mod.Property._MaskSize
import com.olvind.mui.csstype.mod.Property._MaxBlockSize
import com.olvind.mui.csstype.mod.Property._MaxHeight
import com.olvind.mui.csstype.mod.Property._MaxInlineSize
import com.olvind.mui.csstype.mod.Property._MaxLines
import com.olvind.mui.csstype.mod.Property._MaxWidth
import com.olvind.mui.csstype.mod.Property._MinBlockSize
import com.olvind.mui.csstype.mod.Property._MinHeight
import com.olvind.mui.csstype.mod.Property._MinInlineSize
import com.olvind.mui.csstype.mod.Property._MinWidth
import com.olvind.mui.csstype.mod.Property._MozBinding
import com.olvind.mui.csstype.mod.Property._MozBorderBottomColors
import com.olvind.mui.csstype.mod.Property._MozBorderLeftColors
import com.olvind.mui.csstype.mod.Property._MozBorderRightColors
import com.olvind.mui.csstype.mod.Property._MozBorderTopColors
import com.olvind.mui.csstype.mod.Property._MozContextProperties
import com.olvind.mui.csstype.mod.Property._MozForceBrokenImageIcon
import com.olvind.mui.csstype.mod.Property._MozImageRegion
import com.olvind.mui.csstype.mod.Property._MsContentZoomSnap
import com.olvind.mui.csstype.mod.Property._MsFlowFrom
import com.olvind.mui.csstype.mod.Property._MsFlowInto
import com.olvind.mui.csstype.mod.Property._MsGridColumns
import com.olvind.mui.csstype.mod.Property._MsGridRows
import com.olvind.mui.csstype.mod.Property._MsHyphenateLimitChars
import com.olvind.mui.csstype.mod.Property._MsHyphenateLimitLines
import com.olvind.mui.csstype.mod.Property._MsScrollLimitXMax
import com.olvind.mui.csstype.mod.Property._MsScrollLimitYMax
import com.olvind.mui.csstype.mod.Property._MsScrollbar3dlightColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarArrowColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarBaseColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarDarkshadowColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarFaceColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarHighlightColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarShadowColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarTrackColor
import com.olvind.mui.csstype.mod.Property._ObjectPosition
import com.olvind.mui.csstype.mod.Property._Offset
import com.olvind.mui.csstype.mod.Property._OffsetAnchor
import com.olvind.mui.csstype.mod.Property._OffsetPath
import com.olvind.mui.csstype.mod.Property._OffsetRotate
import com.olvind.mui.csstype.mod.Property._Outline
import com.olvind.mui.csstype.mod.Property._OutlineColor
import com.olvind.mui.csstype.mod.Property._OutlineStyle
import com.olvind.mui.csstype.mod.Property._OutlineWidth
import com.olvind.mui.csstype.mod.Property._Overflow
import com.olvind.mui.csstype.mod.Property._OverflowClipMargin
import com.olvind.mui.csstype.mod.Property._OverscrollBehavior
import com.olvind.mui.csstype.mod.Property._PaintOrder
import com.olvind.mui.csstype.mod.Property._Perspective
import com.olvind.mui.csstype.mod.Property._PerspectiveOrigin
import com.olvind.mui.csstype.mod.Property._PlaceContent
import com.olvind.mui.csstype.mod.Property._PlaceItems
import com.olvind.mui.csstype.mod.Property._PlaceSelf
import com.olvind.mui.csstype.mod.Property._Quotes
import com.olvind.mui.csstype.mod.Property._Right
import com.olvind.mui.csstype.mod.Property._Rotate
import com.olvind.mui.csstype.mod.Property._RowGap
import com.olvind.mui.csstype.mod.Property._RubyPosition
import com.olvind.mui.csstype.mod.Property._Scale
import com.olvind.mui.csstype.mod.Property._ScrollPadding
import com.olvind.mui.csstype.mod.Property._ScrollPaddingBlock
import com.olvind.mui.csstype.mod.Property._ScrollPaddingBlockEnd
import com.olvind.mui.csstype.mod.Property._ScrollPaddingBlockStart
import com.olvind.mui.csstype.mod.Property._ScrollPaddingBottom
import com.olvind.mui.csstype.mod.Property._ScrollPaddingInline
import com.olvind.mui.csstype.mod.Property._ScrollPaddingInlineEnd
import com.olvind.mui.csstype.mod.Property._ScrollPaddingInlineStart
import com.olvind.mui.csstype.mod.Property._ScrollPaddingLeft
import com.olvind.mui.csstype.mod.Property._ScrollPaddingRight
import com.olvind.mui.csstype.mod.Property._ScrollPaddingTop
import com.olvind.mui.csstype.mod.Property._ScrollSnapAlign
import com.olvind.mui.csstype.mod.Property._ScrollSnapCoordinate
import com.olvind.mui.csstype.mod.Property._ScrollSnapDestination
import com.olvind.mui.csstype.mod.Property._ScrollSnapPointsX
import com.olvind.mui.csstype.mod.Property._ScrollSnapPointsY
import com.olvind.mui.csstype.mod.Property._ScrollSnapType
import com.olvind.mui.csstype.mod.Property._ScrollbarColor
import com.olvind.mui.csstype.mod.Property._ScrollbarGutter
import com.olvind.mui.csstype.mod.Property._ShapeOutside
import com.olvind.mui.csstype.mod.Property._StopColor
import com.olvind.mui.csstype.mod.Property._Stroke
import com.olvind.mui.csstype.mod.Property._StrokeDasharray
import com.olvind.mui.csstype.mod.Property._TextCombineUpright
import com.olvind.mui.csstype.mod.Property._TextDecoration
import com.olvind.mui.csstype.mod.Property._TextDecorationColor
import com.olvind.mui.csstype.mod.Property._TextDecorationLine
import com.olvind.mui.csstype.mod.Property._TextDecorationSkip
import com.olvind.mui.csstype.mod.Property._TextDecorationThickness
import com.olvind.mui.csstype.mod.Property._TextEmphasis
import com.olvind.mui.csstype.mod.Property._TextEmphasisColor
import com.olvind.mui.csstype.mod.Property._TextEmphasisStyle
import com.olvind.mui.csstype.mod.Property._TextOverflow
import com.olvind.mui.csstype.mod.Property._TextShadow
import com.olvind.mui.csstype.mod.Property._TextSizeAdjust
import com.olvind.mui.csstype.mod.Property._TextUnderlineOffset
import com.olvind.mui.csstype.mod.Property._TextUnderlinePosition
import com.olvind.mui.csstype.mod.Property._Top
import com.olvind.mui.csstype.mod.Property._TouchAction
import com.olvind.mui.csstype.mod.Property._Transform
import com.olvind.mui.csstype.mod.Property._TransformOrigin
import com.olvind.mui.csstype.mod.Property._Transition
import com.olvind.mui.csstype.mod.Property._TransitionProperty
import com.olvind.mui.csstype.mod.Property._TransitionTimingFunction
import com.olvind.mui.csstype.mod.Property._Translate
import com.olvind.mui.csstype.mod.Property._VerticalAlign
import com.olvind.mui.csstype.mod.Property._WebkitBorderBefore
import com.olvind.mui.csstype.mod.Property._WebkitBorderBeforeColor
import com.olvind.mui.csstype.mod.Property._WebkitBorderBeforeStyle
import com.olvind.mui.csstype.mod.Property._WebkitBorderBeforeWidth
import com.olvind.mui.csstype.mod.Property._WebkitBoxReflect
import com.olvind.mui.csstype.mod.Property._WebkitLineClamp
import com.olvind.mui.csstype.mod.Property._WebkitMask
import com.olvind.mui.csstype.mod.Property._WebkitMaskAttachment
import com.olvind.mui.csstype.mod.Property._WebkitMaskClip
import com.olvind.mui.csstype.mod.Property._WebkitMaskComposite
import com.olvind.mui.csstype.mod.Property._WebkitMaskImage
import com.olvind.mui.csstype.mod.Property._WebkitMaskOrigin
import com.olvind.mui.csstype.mod.Property._WebkitMaskPosition
import com.olvind.mui.csstype.mod.Property._WebkitMaskPositionX
import com.olvind.mui.csstype.mod.Property._WebkitMaskPositionY
import com.olvind.mui.csstype.mod.Property._WebkitMaskRepeat
import com.olvind.mui.csstype.mod.Property._WebkitMaskSize
import com.olvind.mui.csstype.mod.Property._WebkitTapHighlightColor
import com.olvind.mui.csstype.mod.Property._WebkitTextFillColor
import com.olvind.mui.csstype.mod.Property._WebkitTextStroke
import com.olvind.mui.csstype.mod.Property._WebkitTextStrokeColor
import com.olvind.mui.csstype.mod.Property._Width
import com.olvind.mui.csstype.mod.Property._WillChange
import com.olvind.mui.csstype.mod.Property._WordSpacing
import com.olvind.mui.csstype.mod.Property._ZIndex
import com.olvind.mui.csstype.mod.Property._Zoom
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - `com.olvind.mui`.csstype.csstypeStrings.`-moz-initial`
  - `com.olvind.mui`.csstype.csstypeStrings.inherit
  - `com.olvind.mui`.csstype.csstypeStrings.initial
  - `com.olvind.mui`.csstype.csstypeStrings.revert
  - `com.olvind.mui`.csstype.csstypeStrings.unset
*/
trait Globals
  extends StObject
     with _AccentColor
     with _AlignContent
     with _AlignItems
     with _AlignSelf
     with _AlignTracks
     with _Animation[Any]
     with _AnimationDirection
     with _AnimationFillMode
     with _AnimationIterationCount
     with _AnimationName
     with _AnimationPlayState
     with _AnimationTimingFunction
     with _AspectRatio
     with _Azimuth
     with _BackdropFilter
     with _Background[Any]
     with _BackgroundAttachment
     with _BackgroundBlendMode
     with _BackgroundClip
     with _BackgroundColor
     with _BackgroundImage
     with _BackgroundOrigin
     with _BackgroundPosition[Any]
     with _BackgroundPositionX[Any]
     with _BackgroundPositionY[Any]
     with _BackgroundRepeat
     with _BackgroundSize[Any]
     with _BaselineShift[Any]
     with _BlockOverflow
     with _BlockSize[Any]
     with _Border[Any]
     with _BorderBlock[Any]
     with _BorderBlockColor
     with _BorderBlockEnd[Any]
     with _BorderBlockEndColor
     with _BorderBlockEndWidth[Any]
     with _BorderBlockStart[Any]
     with _BorderBlockStartColor
     with _BorderBlockStartWidth[Any]
     with _BorderBlockWidth[Any]
     with _BorderBottom[Any]
     with _BorderBottomColor
     with _BorderBottomWidth[Any]
     with _BorderColor
     with _BorderImage
     with _BorderImageRepeat
     with _BorderImageSource
     with _BorderImageWidth[Any]
     with _BorderInline[Any]
     with _BorderInlineColor
     with _BorderInlineEnd[Any]
     with _BorderInlineEndColor
     with _BorderInlineEndWidth[Any]
     with _BorderInlineStart[Any]
     with _BorderInlineStartColor
     with _BorderInlineStartWidth[Any]
     with _BorderInlineWidth[Any]
     with _BorderLeft[Any]
     with _BorderLeftColor
     with _BorderLeftWidth[Any]
     with _BorderRight[Any]
     with _BorderRightColor
     with _BorderRightWidth[Any]
     with _BorderStyle
     with _BorderTop[Any]
     with _BorderTopColor
     with _BorderTopWidth[Any]
     with _BorderWidth[Any]
     with _Bottom[Any]
     with _BoxShadow
     with _CaretColor
     with _Clip
     with _ClipPath
     with _Color
     with _ColorScheme
     with _ColumnCount
     with _ColumnGap[Any]
     with _ColumnRule[Any]
     with _ColumnRuleColor
     with _ColumnRuleStyle
     with _ColumnRuleWidth[Any]
     with _ColumnWidth[Any]
     with _Columns[Any]
     with _Contain
     with _Content
     with _CounterIncrement
     with _CounterReset
     with _CounterSet
     with _Cursor
     with _Display
     with _Fill
     with _Filter
     with _Flex[Any]
     with _FlexBasis[Any]
     with _FlexFlow
     with _FloodColor
     with _Font
     with _FontFamily
     with _FontFeatureSettings
     with _FontLanguageOverride
     with _FontSize[Any]
     with _FontSizeAdjust
     with _FontSmooth[Any]
     with _FontStretch
     with _FontStyle
     with _FontSynthesis
     with _FontVariant
     with _FontVariantAlternates
     with _FontVariantEastAsian
     with _FontVariantLigatures
     with _FontVariantNumeric
     with _FontVariationSettings
     with _FontWeight
     with _Gap[Any]
     with _GlyphOrientationVertical
     with _Grid
     with _GridAutoColumns[Any]
     with _GridAutoFlow
     with _GridAutoRows[Any]
     with _GridTemplate
     with _GridTemplateAreas
     with _GridTemplateColumns[Any]
     with _GridTemplateRows[Any]
     with _HangingPunctuation
     with _Height[Any]
     with _ImageOrientation
     with _ImageResolution
     with _InitialLetter
     with _InlineSize[Any]
     with _Inset[Any]
     with _InsetBlock[Any]
     with _InsetBlockEnd[Any]
     with _InsetBlockStart[Any]
     with _InsetInline[Any]
     with _InsetInlineEnd[Any]
     with _InsetInlineStart[Any]
     with _JustifyContent
     with _JustifyItems
     with _JustifySelf
     with _JustifyTracks
     with _Left[Any]
     with _LetterSpacing[Any]
     with _LightingColor
     with _LineClamp
     with _LineHeight[Any]
     with _ListStyle
     with _ListStyleImage
     with _ListStyleType
     with _Margin[Any]
     with _MarginBlock[Any]
     with _MarginBlockEnd[Any]
     with _MarginBlockStart[Any]
     with _MarginBottom[Any]
     with _MarginInline[Any]
     with _MarginInlineEnd[Any]
     with _MarginInlineStart[Any]
     with _MarginLeft[Any]
     with _MarginRight[Any]
     with _MarginTop[Any]
     with _Marker
     with _MarkerEnd
     with _MarkerMid
     with _MarkerStart
     with _Mask[Any]
     with _MaskBorder
     with _MaskBorderRepeat
     with _MaskBorderSource
     with _MaskBorderWidth[Any]
     with _MaskClip
     with _MaskComposite
     with _MaskImage
     with _MaskMode
     with _MaskOrigin
     with _MaskPosition[Any]
     with _MaskRepeat
     with _MaskSize[Any]
     with _MaxBlockSize[Any]
     with _MaxHeight[Any]
     with _MaxInlineSize[Any]
     with _MaxLines
     with _MaxWidth[Any]
     with _MinBlockSize[Any]
     with _MinHeight[Any]
     with _MinInlineSize[Any]
     with _MinWidth[Any]
     with _MozBinding
     with _MozBorderBottomColors
     with _MozBorderLeftColors
     with _MozBorderRightColors
     with _MozBorderTopColors
     with _MozContextProperties
     with _MozForceBrokenImageIcon
     with _MozImageRegion
     with _MsContentZoomSnap
     with _MsFlowFrom
     with _MsFlowInto
     with _MsGridColumns[Any]
     with _MsGridRows[Any]
     with _MsHyphenateLimitChars
     with _MsHyphenateLimitLines
     with _MsScrollLimitXMax[Any]
     with _MsScrollLimitYMax[Any]
     with _MsScrollbar3dlightColor
     with _MsScrollbarArrowColor
     with _MsScrollbarBaseColor
     with _MsScrollbarDarkshadowColor
     with _MsScrollbarFaceColor
     with _MsScrollbarHighlightColor
     with _MsScrollbarShadowColor
     with _MsScrollbarTrackColor
     with _ObjectPosition[Any]
     with _Offset[Any]
     with _OffsetAnchor[Any]
     with _OffsetPath
     with _OffsetRotate
     with _Outline[Any]
     with _OutlineColor
     with _OutlineStyle
     with _OutlineWidth[Any]
     with _Overflow
     with _OverflowClipMargin[Any]
     with _OverscrollBehavior
     with _PaintOrder
     with _Perspective[Any]
     with _PerspectiveOrigin[Any]
     with _PlaceContent
     with _PlaceItems
     with _PlaceSelf
     with _Quotes
     with _Right[Any]
     with _Rotate
     with _RowGap[Any]
     with _RubyPosition
     with _Scale
     with _ScrollPadding[Any]
     with _ScrollPaddingBlock[Any]
     with _ScrollPaddingBlockEnd[Any]
     with _ScrollPaddingBlockStart[Any]
     with _ScrollPaddingBottom[Any]
     with _ScrollPaddingInline[Any]
     with _ScrollPaddingInlineEnd[Any]
     with _ScrollPaddingInlineStart[Any]
     with _ScrollPaddingLeft[Any]
     with _ScrollPaddingRight[Any]
     with _ScrollPaddingTop[Any]
     with _ScrollSnapAlign
     with _ScrollSnapCoordinate[Any]
     with _ScrollSnapDestination[Any]
     with _ScrollSnapPointsX
     with _ScrollSnapPointsY
     with _ScrollSnapType
     with _ScrollbarColor
     with _ScrollbarGutter
     with _ShapeOutside
     with _StopColor
     with _Stroke
     with _StrokeDasharray[Any]
     with _TextCombineUpright
     with _TextDecoration[Any]
     with _TextDecorationColor
     with _TextDecorationLine
     with _TextDecorationSkip
     with _TextDecorationThickness[Any]
     with _TextEmphasis
     with _TextEmphasisColor
     with _TextEmphasisStyle
     with _TextOverflow
     with _TextShadow
     with _TextSizeAdjust
     with _TextUnderlineOffset[Any]
     with _TextUnderlinePosition
     with _Top[Any]
     with _TouchAction
     with _Transform
     with _TransformOrigin[Any]
     with _Transition[Any]
     with _TransitionProperty
     with _TransitionTimingFunction
     with _Translate[Any]
     with _VerticalAlign[Any]
     with _WebkitBorderBefore[Any]
     with _WebkitBorderBeforeColor
     with _WebkitBorderBeforeStyle
     with _WebkitBorderBeforeWidth[Any]
     with _WebkitBoxReflect[Any]
     with _WebkitLineClamp
     with _WebkitMask[Any]
     with _WebkitMaskAttachment
     with _WebkitMaskClip
     with _WebkitMaskComposite
     with _WebkitMaskImage
     with _WebkitMaskOrigin
     with _WebkitMaskPosition[Any]
     with _WebkitMaskPositionX[Any]
     with _WebkitMaskPositionY[Any]
     with _WebkitMaskRepeat
     with _WebkitMaskSize[Any]
     with _WebkitTapHighlightColor
     with _WebkitTextFillColor
     with _WebkitTextStroke[Any]
     with _WebkitTextStrokeColor
     with _Width[Any]
     with _WillChange
     with _WordSpacing[Any]
     with _ZIndex
     with _Zoom
object Globals {
  
  inline def `-moz-initial`: com.olvind.mui.csstype.csstypeStrings.`-moz-initial` = "-moz-initial".asInstanceOf[com.olvind.mui.csstype.csstypeStrings.`-moz-initial`]
  
  inline def inherit: com.olvind.mui.csstype.csstypeStrings.inherit = "inherit".asInstanceOf[com.olvind.mui.csstype.csstypeStrings.inherit]
  
  inline def initial: com.olvind.mui.csstype.csstypeStrings.initial = "initial".asInstanceOf[com.olvind.mui.csstype.csstypeStrings.initial]
  
  inline def revert: com.olvind.mui.csstype.csstypeStrings.revert = "revert".asInstanceOf[com.olvind.mui.csstype.csstypeStrings.revert]
  
  inline def unset: com.olvind.mui.csstype.csstypeStrings.unset = "unset".asInstanceOf[com.olvind.mui.csstype.csstypeStrings.unset]
}
