package com.olvind.mui.csstype.mod.DataType

import com.olvind.mui.csstype.mod.Property._AccentColor
import com.olvind.mui.csstype.mod.Property._BackgroundColor
import com.olvind.mui.csstype.mod.Property._Border
import com.olvind.mui.csstype.mod.Property._BorderBlock
import com.olvind.mui.csstype.mod.Property._BorderBlockColor
import com.olvind.mui.csstype.mod.Property._BorderBlockEnd
import com.olvind.mui.csstype.mod.Property._BorderBlockEndColor
import com.olvind.mui.csstype.mod.Property._BorderBlockStart
import com.olvind.mui.csstype.mod.Property._BorderBlockStartColor
import com.olvind.mui.csstype.mod.Property._BorderBottom
import com.olvind.mui.csstype.mod.Property._BorderBottomColor
import com.olvind.mui.csstype.mod.Property._BorderColor
import com.olvind.mui.csstype.mod.Property._BorderInline
import com.olvind.mui.csstype.mod.Property._BorderInlineColor
import com.olvind.mui.csstype.mod.Property._BorderInlineEnd
import com.olvind.mui.csstype.mod.Property._BorderInlineEndColor
import com.olvind.mui.csstype.mod.Property._BorderInlineStart
import com.olvind.mui.csstype.mod.Property._BorderInlineStartColor
import com.olvind.mui.csstype.mod.Property._BorderLeft
import com.olvind.mui.csstype.mod.Property._BorderLeftColor
import com.olvind.mui.csstype.mod.Property._BorderRight
import com.olvind.mui.csstype.mod.Property._BorderRightColor
import com.olvind.mui.csstype.mod.Property._BorderTop
import com.olvind.mui.csstype.mod.Property._BorderTopColor
import com.olvind.mui.csstype.mod.Property._CaretColor
import com.olvind.mui.csstype.mod.Property._ColumnRule
import com.olvind.mui.csstype.mod.Property._ColumnRuleColor
import com.olvind.mui.csstype.mod.Property._FloodColor
import com.olvind.mui.csstype.mod.Property._LightingColor
import com.olvind.mui.csstype.mod.Property._MozBorderBottomColors
import com.olvind.mui.csstype.mod.Property._MozBorderLeftColors
import com.olvind.mui.csstype.mod.Property._MozBorderRightColors
import com.olvind.mui.csstype.mod.Property._MozBorderTopColors
import com.olvind.mui.csstype.mod.Property._MsScrollbar3dlightColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarArrowColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarBaseColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarDarkshadowColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarFaceColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarHighlightColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarShadowColor
import com.olvind.mui.csstype.mod.Property._MsScrollbarTrackColor
import com.olvind.mui.csstype.mod.Property._Outline
import com.olvind.mui.csstype.mod.Property._OutlineColor
import com.olvind.mui.csstype.mod.Property._StopColor
import com.olvind.mui.csstype.mod.Property._TextDecoration
import com.olvind.mui.csstype.mod.Property._TextDecorationColor
import com.olvind.mui.csstype.mod.Property._TextEmphasis
import com.olvind.mui.csstype.mod.Property._TextEmphasisColor
import com.olvind.mui.csstype.mod.Property._WebkitBorderBefore
import com.olvind.mui.csstype.mod.Property._WebkitBorderBeforeColor
import com.olvind.mui.csstype.mod.Property._WebkitTapHighlightColor
import com.olvind.mui.csstype.mod.Property._WebkitTextFillColor
import com.olvind.mui.csstype.mod.Property._WebkitTextStroke
import com.olvind.mui.csstype.mod.Property._WebkitTextStrokeColor
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

trait _Color
  extends StObject
     with _AccentColor
     with _BackgroundColor
     with _Border[Any]
     with _BorderBlock[Any]
     with _BorderBlockColor
     with _BorderBlockEnd[Any]
     with _BorderBlockEndColor
     with _BorderBlockStart[Any]
     with _BorderBlockStartColor
     with _BorderBottom[Any]
     with _BorderBottomColor
     with _BorderColor
     with _BorderInline[Any]
     with _BorderInlineColor
     with _BorderInlineEnd[Any]
     with _BorderInlineEndColor
     with _BorderInlineStart[Any]
     with _BorderInlineStartColor
     with _BorderLeft[Any]
     with _BorderLeftColor
     with _BorderRight[Any]
     with _BorderRightColor
     with _BorderTop[Any]
     with _BorderTopColor
     with _CaretColor
     with com.olvind.mui.csstype.mod.Property._Color
     with _ColumnRule[Any]
     with _ColumnRuleColor
     with _FinalBgLayer[Any]
     with _FloodColor
     with _LightingColor
     with _MozBorderBottomColors
     with _MozBorderLeftColors
     with _MozBorderRightColors
     with _MozBorderTopColors
     with _MsScrollbar3dlightColor
     with _MsScrollbarArrowColor
     with _MsScrollbarBaseColor
     with _MsScrollbarDarkshadowColor
     with _MsScrollbarFaceColor
     with _MsScrollbarHighlightColor
     with _MsScrollbarShadowColor
     with _MsScrollbarTrackColor
     with _Outline[Any]
     with _OutlineColor
     with _Paint
     with _StopColor
     with _TextDecoration[Any]
     with _TextDecorationColor
     with _TextEmphasis
     with _TextEmphasisColor
     with _WebkitBorderBefore[Any]
     with _WebkitBorderBeforeColor
     with _WebkitTapHighlightColor
     with _WebkitTextFillColor
     with _WebkitTextStroke[Any]
     with _WebkitTextStrokeColor
