name: CI Build
on:
  pull_request:
    branches: [ 'master' ]

jobs:
  build-scalajs-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          apps: sbt

      - uses: coursier/cache-action@v6

      - name: Build
        run: sbt st-material-ui-icons-scalajs-react/compile

  build-slinky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          apps: sbt

      - uses: coursier/cache-action@v6

      - name: Build
        run: sbt st-material-ui-icons-slinky/compile

