package com.olvind.mui.csstype.mod.DataType

import com.olvind.mui.csstype.mod.Property._Border
import com.olvind.mui.csstype.mod.Property._BorderBlock
import com.olvind.mui.csstype.mod.Property._BorderBlockEnd
import com.olvind.mui.csstype.mod.Property._BorderBlockEndWidth
import com.olvind.mui.csstype.mod.Property._BorderBlockStart
import com.olvind.mui.csstype.mod.Property._BorderBlockStartWidth
import com.olvind.mui.csstype.mod.Property._BorderBlockWidth
import com.olvind.mui.csstype.mod.Property._BorderBottom
import com.olvind.mui.csstype.mod.Property._BorderBottomWidth
import com.olvind.mui.csstype.mod.Property._BorderInline
import com.olvind.mui.csstype.mod.Property._BorderInlineEnd
import com.olvind.mui.csstype.mod.Property._BorderInlineEndWidth
import com.olvind.mui.csstype.mod.Property._BorderInlineStart
import com.olvind.mui.csstype.mod.Property._BorderInlineStartWidth
import com.olvind.mui.csstype.mod.Property._BorderInlineWidth
import com.olvind.mui.csstype.mod.Property._BorderLeft
import com.olvind.mui.csstype.mod.Property._BorderLeftWidth
import com.olvind.mui.csstype.mod.Property._BorderRight
import com.olvind.mui.csstype.mod.Property._BorderRightWidth
import com.olvind.mui.csstype.mod.Property._BorderTop
import com.olvind.mui.csstype.mod.Property._BorderTopWidth
import com.olvind.mui.csstype.mod.Property._BorderWidth
import com.olvind.mui.csstype.mod.Property._ColumnRule
import com.olvind.mui.csstype.mod.Property._ColumnRuleWidth
import com.olvind.mui.csstype.mod.Property._Outline
import com.olvind.mui.csstype.mod.Property._OutlineWidth
import com.olvind.mui.csstype.mod.Property._WebkitBorderBefore
import com.olvind.mui.csstype.mod.Property._WebkitBorderBeforeWidth
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

trait _LineWidth[TLength]
  extends StObject
     with _Border[TLength]
     with _BorderBlock[TLength]
     with _BorderBlockEnd[TLength]
     with _BorderBlockEndWidth[TLength]
     with _BorderBlockStart[TLength]
     with _BorderBlockStartWidth[TLength]
     with _BorderBlockWidth[TLength]
     with _BorderBottom[TLength]
     with _BorderBottomWidth[TLength]
     with _BorderInline[TLength]
     with _BorderInlineEnd[TLength]
     with _BorderInlineEndWidth[TLength]
     with _BorderInlineStart[TLength]
     with _BorderInlineStartWidth[TLength]
     with _BorderInlineWidth[TLength]
     with _BorderLeft[TLength]
     with _BorderLeftWidth[TLength]
     with _BorderRight[TLength]
     with _BorderRightWidth[TLength]
     with _BorderTop[TLength]
     with _BorderTopWidth[TLength]
     with _BorderWidth[TLength]
     with _ColumnRule[TLength]
     with _ColumnRuleWidth[TLength]
     with _Outline[TLength]
     with _OutlineWidth[TLength]
     with _WebkitBorderBefore[TLength]
     with _WebkitBorderBeforeWidth[TLength]
